In [1]:
import pandas as pd
data=pd.read_csv('glass(For SVM Program).csv')
data.head()

Id       RI     Na    Mg    Al    Si      K    Ca   Ba   Fe  Type
0   1  1.52101  13.64  4.49  1.10  71.78  0.06  8.75  0.0  0.0     1
1   2  1.51761  13.89  3.60  1.36  72.73  0.48  7.83  0.0  0.0     1
2   3  1.51618  13.53  3.55  1.54  72.99  0.39  7.78  0.0  0.0     1
3   4  1.51766  13.21  3.69  1.29  72.61  0.57  8.22  0.0  0.0     1
4   5  1.51742  13.27  3.62  1.24  73.08  0.55  8.07  0.0  0.0     1

In [2]:
x=data.drop('Type',axis=1)
y=data['Type']

In [3]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.25)

In [4]:
from sklearn.svm import SVC
import numpy as np

In [5]:
X=np.array([[3,4],[1,4],[2,3],[6,-1],[7,-1],[5,-3]])
Y=np.array([-1,-1,-1,1,1,1])

In [6]:
l=SVC(C=1e5,kernel='linear')
l.fit(X,Y)

SVC(C=100000.0, kernel='linear')

In [7]:
print('w= ',l.coef_)
print('b= ',l.intercept_)
print('Indices of support vectors= ',l.support_)
print('Support vectors= ',l.support_vectors_)
print('No. of support vectors from each class= ',l.n_support_)
print('coefficient of support vectors in decision function= ',np.abs(l.dual_coef_))

w=  [[ 0.25 -0.25]]
b=  [-0.75]
Indices of support vectors=  [2 3]
Support vectors=  [[ 2.  3.]
 [ 6. -1.]]
No. of support vectors from each class=  [1 1]
coefficient of support vectors in decision function=  [[0.0625 0.0625]]


In [8]:
model=SVC(kernel='linear')
model.fit(x_train,y_train)
y_pred=model.predict(x_test)

In [9]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
print(accuracy_score(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

1.0
[[17  0  0  0  0  0]
 [ 0 22  0  0  0  0]
 [ 0  0  6  0  0  0]
 [ 0  0  0  2  0  0]
 [ 0  0  0  0  2  0]
 [ 0  0  0  0  0  5]]
              precision    recall  f1-score   support

           1       1.00      1.00      1.00        17
           2       1.00      1.00      1.00        22
           3       1.00      1.00      1.00         6
           5       1.00      1.00      1.00         2
           6       1.00      1.00      1.00         2
           7       1.00      1.00      1.00         5

    accuracy                           1.00        54
   macro avg       1.00      1.00      1.00        54
weighted avg       1.00      1.00      1.00        54



In [10]:
model1=SVC(kernel='sigmoid')
model2=SVC(kernel='poly')
model3=SVC(kernel='rbf')
model1.fit(x_train,y_train)
model2.fit(x_train,y_train)
model3.fit(x_train,y_train)
y_pred1=model1.predict(x_test)
y_pred2=model2.predict(x_test)
y_pred3=model3.predict(x_test)
print("prediction by model1 ",accuracy_score(y_test,y_pred1))
print("prediction by model2",accuracy_score(y_test,y_pred2))
print("prediction by model3",accuracy_score(y_test,y_pred1))

prediction by model1  0.6481481481481481
prediction by model2 0.9074074074074074
prediction by model3 0.6481481481481481
