In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix
from sklearn.svm import SVC
from sklearn.model_selection import train_test_split,GridSearchCV

In [3]:
data=pd.read_csv("glass(For SVM Program).csv")
data.head()

Id       RI     Na    Mg    Al    Si      K    Ca   Ba   Fe  Type
0   1  1.52101  13.64  4.49  1.10  71.78  0.06  8.75  0.0  0.0     1
1   2  1.51761  13.89  3.60  1.36  72.73  0.48  7.83  0.0  0.0     1
2   3  1.51618  13.53  3.55  1.54  72.99  0.39  7.78  0.0  0.0     1
3   4  1.51766  13.21  3.69  1.29  72.61  0.57  8.22  0.0  0.0     1
4   5  1.51742  13.27  3.62  1.24  73.08  0.55  8.07  0.0  0.0     1

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 214 entries, 0 to 213
Data columns (total 11 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Id      214 non-null    int64  
 1   RI      214 non-null    float64
 2   Na      214 non-null    float64
 3   Mg      214 non-null    float64
 4   Al      214 non-null    float64
 5   Si      214 non-null    float64
 6   K       214 non-null    float64
 7   Ca      214 non-null    float64
 8   Ba      214 non-null    float64
 9   Fe      214 non-null    float64
 10  Type    214 non-null    int64  
dtypes: float64(9), int64(2)
memory usage: 18.5 KB


In [5]:
x=data.drop(['Type'],axis=1)
y=data['Type']

In [6]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3)

In [7]:
ml=SVC(kernel='linear')
ml.fit(x_train,y_train)

SVC(kernel='linear')

In [8]:
print(ml.support_vectors_)

[[7.00000e+01 1.52300e+00 1.33100e+01 3.58000e+00 8.20000e-01 7.19900e+01
  1.20000e-01 1.01700e+01 0.00000e+00 3.00000e-02]
 [1.46000e+02 1.51839e+00 1.28500e+01 3.67000e+00 1.24000e+00 7.25700e+01
  6.20000e-01 8.68000e+00 0.00000e+00 3.50000e-01]
 [7.20000e+01 1.51848e+00 1.36400e+01 3.87000e+00 1.27000e+00 7.19600e+01
  5.40000e-01 8.32000e+00 0.00000e+00 3.20000e-01]
 [1.61000e+02 1.51832e+00 1.33300e+01 3.34000e+00 1.54000e+00 7.21400e+01
  5.60000e-01 8.99000e+00 0.00000e+00 0.00000e+00]
 [1.47000e+02 1.51769e+00 1.36500e+01 3.66000e+00 1.11000e+00 7.27700e+01
  1.10000e-01 8.60000e+00 0.00000e+00 0.00000e+00]
 [1.65000e+02 1.51915e+00 1.27300e+01 1.85000e+00 1.86000e+00 7.26900e+01
  6.00000e-01 1.00900e+01 0.00000e+00 0.00000e+00]
 [1.72000e+02 1.51316e+00 1.30200e+01 0.00000e+00 3.04000e+00 7.04800e+01
  6.21000e+00 6.96000e+00 0.00000e+00 0.00000e+00]
 [1.64000e+02 1.51514e+00 1.40100e+01 2.68000e+00 3.50000e+00 6.98900e+01
  1.68000e+00 5.87000e+00 2.20000e+00 0.00000e+00]


In [10]:
print(ml.n_support_)

[1 2 2 4 3 2]


In [11]:
y_pred=ml.predict(x_test)
print(accuracy_score(y_test,y_pred))

0.9846153846153847


In [12]:
print(confusion_matrix(y_test,y_pred))

[[24  0  0  0  0  0]
 [ 0 23  0  0  0  0]
 [ 0  0  3  0  0  0]
 [ 0  0  0  4  1  0]
 [ 0  0  0  0  1  0]
 [ 0  0  0  0  0  9]]


In [13]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           1       1.00      1.00      1.00        24
           2       1.00      1.00      1.00        23
           3       1.00      1.00      1.00         3
           5       1.00      0.80      0.89         5
           6       0.50      1.00      0.67         1
           7       1.00      1.00      1.00         9

    accuracy                           0.98        65
   macro avg       0.92      0.97      0.93        65
weighted avg       0.99      0.98      0.99        65



In [14]:
model1=SVC(kernel='sigmoid',gamma=0.001)
model2=SVC(kernel='poly',degree=3)
model3=SVC(kernel='rbf')

In [15]:
model1.fit(x_train,y_train)
model2.fit(x_train,y_train)
model3.fit(x_train,y_train)

SVC()

In [16]:
y_pred1=model1.predict(x_test)
y_pred2=model2.predict(x_test)
y_pred3=model3.predict(x_test)

In [20]:
print(accuracy_score(y_test,y_pred1))

0.35384615384615387


In [18]:
print(accuracy_score(y_test,y_pred2))

0.9230769230769231


In [19]:
print(accuracy_score(y_test,y_pred3))

0.8461538461538461
